# Generated by Django 3.2.12 on 2022-03-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20210206_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='education',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
